language: go

sudo: false

services:
    - docker

go:
    - 1.8.x
    - 1.9.x
    - tip

matrix:
    allow_failures:
        - go: tip

before_install:
    - mkdir -p $HOME/bin
    - curl -sL http://get.binhq.io/gitbin | DEST=$HOME/bin bash
    - gitbin get Masterminds/glide 0.12.3 -o $HOME/bin
    - make envcheck

install: make setup

before_script:
    - export VERSION=${TRAVIS_TAG:-$TRAVIS_BRANCH}
    - export $(make varexport-DOCKER_IMAGE)

script:
    - TEST_RANDOMIZE=true make TAGS="acceptance integration" ARGS="-v" check
    - if [[ $TRAVIS_TAG = "$VERSION" ]]; then export DOCKER_LATEST=true; fi
    - make docker

before_deploy: docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
    provider: script
    skip_cleanup: true
    script: docker push $DOCKER_IMAGE
    on:
        all_branches: true
        condition: $TRAVIS_GO_VERSION =~ ^1\.9(\.[0-9]+)?$
